version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myappuserpassword
      POSTGRES_DB: tabletop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      args:
        ENV_FILE_PATH: /tabletop-homebrew-app/.env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
volumes:
  postgres_data: