version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myappuser
      POSTGRES_PASSWORD: myappuserpassword
      POSTGRES_DB: tabletop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://myappuser:myappuserpassword@db:5432/tabletop_db
      SECRET_KEY: your_secret_key
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  postgres_data: